version: '3.8'

services:
  llm:
    build: llm
    container_name: llm
    restart: always
    volumes:
      - ./uvicorn_data:/server/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  haproxy:
    image: haproxy:2.8.7
    container_name: haproxy
    restart: always
    ports:
      - 8080:8080
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - ./docker/haproxy:/usr/local/etc/haproxy
    networks:
      - app_network

networks:
  app_network:
