---
apiVersion: v1
kind: Service
metadata:
  name: cloud-server2
  namespace: psd2
  labels:
    app: cloud
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
      name: server
  selector:
    app: cloud
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
  namespace: psd2
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      namespace: psd2
      labels:
        app: cloud
    spec:
      containers:
        - image: ghcr.io/mcdulltii/cloud-server2:latest
          name: cloud-server2
          stdin: true
          tty: true
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloud-hpa
  namespace: psd2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 1k
status: {}
